In [1]:
from pathlib import Path
from datetime import datetime
import numpy as np
import pandas as pd
from sklearn import preprocessing
pd.set_option("display.max_columns", 100)
from sklearn.metrics import f1_score
DATA_PATH = Path.cwd().parent / "ML project" 
from imblearn.combine import SMOTETomek, SMOTEENN
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Normalizer
from sklearn.pipeline import Pipeline
from sklearn.impute import MissingIndicator
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
from lightgbm import LGBMClassifier
from sklearn.model_selection import KFold
from imblearn.over_sampling import SMOTE, SVMSMOTE
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import Normalizer
RANDOM_SEED = 6    # Set a random seed for reproducibility!

In [2]:

from math import cos, asin, sqrt, pi

def distanceLong(lat1, lon1, lat2, lon2):
    p = pi/180
    latDiff = (lat2-lat1)*p
    lonDiff = (lon2-lon1)*p
    coslat1 = np.cos(lat1*p)
    coslat2 = np.cos(lat2*p)
    coslondiff = np.cos(lonDiff)
    coslatdiff = np.cos(latDiff)
    a = 0.5 - coslatdiff/2 + coslat1 * coslat2 * (1-coslondiff)/2
    return 12742 * (np.arcsin(a**0.5)) 

In [3]:

def formatdata(dataFrame):
    dataFrame['pickup_time'] = dataFrame['pickup_time']+ '.099'
    dataFrame['pickup_time'] = dataFrame['pickup_time'].apply(lambda x:  x.replace("/","-"))
    dataFrame['drop_time'] = dataFrame['drop_time']+ '.099'

    pd.to_datetime(dataFrame['pickup_time'], format='%m-%d-%Y %H:%M:%S.%f', errors='ignore')
    pd.to_datetime(dataFrame['drop_time'], format='%m/%d/%Y %H:%M:%S.%f', errors='ignore')
    
    dataFrame['pickup_time'] = dataFrame['pickup_time'].apply(lambda x: datetime.timestamp(datetime.strptime(x,'%m-%d-%Y %H:%M.%f')))
    dataFrame['drop_time'] = dataFrame['drop_time'].apply(lambda x: datetime.timestamp(datetime.strptime(x,'%m/%d/%Y %H:%M.%f')))

    dataFrame['timediff'] =  dataFrame['drop_time'] - dataFrame['pickup_time']
   # dataFrame['timediff1'] =  dataFrame['timediff']**2
    dataFrame['distance'] = distanceLong(dataFrame['drop_lat'],dataFrame['drop_lon'],dataFrame['pick_lat'],dataFrame['pick_lon'])*100
    #dataFrame['distance'] = ((dataFrame['drop_lat']-dataFrame['pick_lat'])**2+(dataFrame['drop_lon']-dataFrame['pick_lon'])**2)**0.5
    #dataFrame['unit_meter_waiting_fair'] = dataFrame['meter_waiting_fare'] / dataFrame['meter_waiting']
    #print(dataFrame['unit_meter_waiting_fair'])
    
    #dataFrame['_fare'] = dataFrame['fare'] - dataFrame['additional_fare'] 
    #dataFrame['tripDuration'] = dataFrame['duration'] - dataFrame['meter_waiting']
    
    
    return dataFrame

 
bestDegree = 0
bestBias = False
bestInteraction = False
bestscore = 0

In [4]:

solver = 'lbfgs'
alpha = 0.2
hidden_layer_sizes=(10,2 )
random_state=2
max_iter= 10000000
activation='tanh'
estimatorsX=MLPClassifier(solver=solver, alpha=alpha, hidden_layer_sizes=hidden_layer_sizes, random_state=random_state,
                         max_iter=max_iter, activation=activation)

min_child_weight=1.5
max_depth=5
gamma=2.5
colsample_bytree=0.8
subsample=0.8
n_estimators=200
threads = 4
estimatorsXX = XGBClassifier(min_child_weight=min_child_weight,max_depth=max_depth, 
                           gamma=gamma,colsample_bytree=colsample_bytree,subsample=subsample,
                           n_estimators=n_estimators, n_jobs=threads
                          )
params = { 'min_child_weight': [1.5,2,2.5],'max_depth':[8,9,7]}

#estimatorsY = LGBMClassifier(boosting_type='gbdt', num_leaves=40, max_depth=6,learning_rate=0.2,
 #                          n_estimators=1000,random_state=42)

estimators = BaggingClassifier(base_estimator=estimatorsXX,n_estimators=10,max_samples=0.65,
                             max_features=1.0, random_state=1,bootstrap=False)
#estimators = VotingClassifier( [('xgb', estimatorsX), ('mlp', estimatorsY)], weights=[1,1])
#estimators = GridSearchCV(estimator=estimatorsXX, param_grid=params, cv=10)


train_df = pd.read_csv(
    DATA_PATH / "train.csv", 
    index_col="tripid"
)



train_df['label'] = train_df['label'].map({"correct":1, "incorrect":0})
train_df_cols = train_df.columns.values
li = list(train_df_cols)
features_df = train_df[li[0:-1]]
labels_df = train_df[li[-1]]
features_df = formatdata(features_df)
features_df = features_df.fillna(features_df.mean())
numeric_cols = features_df.columns[features_df.dtypes != object].values



def removeColumns(npArry, columnNames):
    li = list(npArry)
    for i in columnNames:
        li.remove(i)
    return np.array(li)


def powerAll(data_frame, exceptList,power):
    allColumns = data_frame.columns.values
    for i in allColumns:
        if(i not in exceptList ):
            data_frame[i] = data_frame[i]**power
 

#nothing
exceptList = []
power = 1

numeric_cols = removeColumns(numeric_cols,['drop_time', 'pickup_time','drop_lat','drop_lon','pick_lat','pick_lon'
                                             ])  

#powerAll(features_df, exceptList,1)
#exceptList = features_df.columns[features_df.dtypes == "object"].values
#polyList1 = ['meter_waiting_fare','fare']
polyList1 = ['additional_fare','distance','meter_waiting']
polyList2 = ['timediff','distance']
polyList3 = ['meter_waiting','duration']
polyList4 = ['timediff','fare']
polyList5 = ['distance','fare']
polyList6 = ['meter_waiting_fare','additional_fare']
numeric_preprocessing_steps = Pipeline([ 
    ('standard_scaler', StandardScaler()),
])




feature_transformer2 = PolynomialFeatures(degree=4, include_bias=False,interaction_only=False)
            
feature_transformer3 = PolynomialFeatures(degree=4, include_bias=True,interaction_only=False)
feature_transformer4 = PolynomialFeatures(degree=4, include_bias=True,interaction_only=False)
feature_transformer5 = PolynomialFeatures(degree=4, include_bias=True,interaction_only=False)
feature_transformer6 = PolynomialFeatures(degree=7, include_bias=False,interaction_only=False)
            
normalizer_transformer = Normalizer(norm ='l2')
            # create the preprocessor stage of final pipeline
            # each entry in the transformer list is a tuple of
            # (name you choose, sklearn transformer, list of columns)
preprocessor = ColumnTransformer(
    transformers = [
        
        ('poly2', feature_transformer2,polyList2),
        ('poly3', feature_transformer3,polyList3),
        ('poly4', feature_transformer4,polyList4),
        ('poly5', feature_transformer5,polyList5),
        ('poly6', feature_transformer6,polyList6),
        ("numeric", numeric_preprocessing_steps, numeric_cols),
        ("nomalizer", normalizer_transformer, numeric_cols)
    ],
    remainder = "drop"
)



FileNotFoundError: [Errno 2] File C:\Users\User\Desktop\ML project\tosubmit\ML project\train.csv does not exist: 'C:\\Users\\User\\Desktop\\ML project\\tosubmit\\ML project\\train.csv'

In [5]:
clf1 = ''
clf2 = ''
clf3 = ''
clf4 = ''
clf5 = ''
statesList = [3,6,42,2,1]
for i in statesList:    
    kf = KFold(n_splits=10, random_state=i, shuffle=True)


    kf.get_n_splits(features_df)
    test_features_df = pd.read_csv(DATA_PATH / "test.csv", 
                                   index_col="tripid")

    test_features_df = formatdata(test_features_df)
    powerAll(test_features_df, exceptList,power)

    bestscore = 0
    bestModelx = ""




    for train_index, test_index in kf.split(features_df):

        X_train, X_eval, y_train, y_eval = features_df.iloc[train_index], features_df.iloc[test_index],labels_df.iloc[train_index], labels_df.iloc[test_index]
        full_pipeline = Pipeline([
            ("preprocessor", preprocessor),
            ("estimators", estimators),
        ])
        full_pipeline.fit(X_train, y_train)
        preds = full_pipeline.predict(X_eval)
        y_preds = pd.DataFrame(
            preds,
            index = y_eval.index
        )
        test_probas = full_pipeline.predict(test_features_df)
        test_preds = pd.DataFrame(
            {'prediction':test_probas},
            index = test_features_df.index
        )
        f1 = f1_score(y_eval, y_preds)
        if(f1 > bestscore):
            bestscore = f1
            bestModelx = test_preds


    
    
    test_preds1 = bestModelx
    
    if(i == 3):
        
        clf1 =bestModelx
        print(clf1.prediction.value_counts())
    elif(i==6):
        clf2 = bestModelx
        print(clf2.prediction.value_counts())
    elif(i==2):
        clf4 = bestModelx
        print(clf4.prediction.value_counts())
    elif(i==1):
        clf5 = bestModelx
        print(clf5.prediction.value_counts())
    else:
        clf3 =bestModelx
        print(clf3.prediction.value_counts())
    print('bestscore', bestscore)


1    8161
0     415
Name: prediction, dtype: int64
bestscore 0.9825119236883942
1    8163
0     413
Name: prediction, dtype: int64
bestscore 0.9803416048984853
1    8160
0     416
Name: prediction, dtype: int64
bestscore 0.9792191435768262
1    8158
0     418
Name: prediction, dtype: int64
bestscore 0.9794887977279899
1    8166
0     410
Name: prediction, dtype: int64
bestscore 0.9807145115396776


In [6]:


print(clf4.equals(clf1))
print(clf1.prediction.value_counts())

False
1    8161
0     415
Name: prediction, dtype: int64


In [7]:
test_preds1 = clf1
print(test_preds1.prediction.value_counts())

test_preds2 = clf2
print(test_preds2.prediction.value_counts())

test_preds3 = clf3
print(test_preds3.prediction.value_counts())

test_preds4 = clf4
print(test_preds4.prediction.value_counts())

test_preds5 = clf5
print(test_preds5.prediction.value_counts())

final_preds = clf1

for index, row in test_preds1.iterrows():
    df1_row_value =  test_preds1.loc[index].prediction
    df2_row_value =  test_preds2.loc[index].prediction
    df3_row_value =  test_preds3.loc[index].prediction
    df4_row_value =  test_preds4.loc[index].prediction
    df5_row_value =  test_preds5.loc[index].prediction

    if(df1_row_value + df2_row_value + df3_row_value + df4_row_value + df5_row_value >= 3):
        final_preds.loc[index].prediction = 1
    else:
        final_preds.loc[index].prediction = 0
    
print(final_preds.prediction.value_counts())






1    8161
0     415
Name: prediction, dtype: int64
1    8163
0     413
Name: prediction, dtype: int64
1    8160
0     416
Name: prediction, dtype: int64
1    8158
0     418
Name: prediction, dtype: int64
1    8166
0     410
Name: prediction, dtype: int64
1    8164
0     412
Name: prediction, dtype: int64


In [8]:
#0.9828134945894335 state 3 k=10
#0.9816188326346339 state 6 k=10
test_preds1.to_csv(DATA_PATH / 'my_submission.csv', index=True)

In [ ]:

solver = 'lbfgs'
alpha = 0.2
hidden_layer_sizes=(10,2 )
random_state=2
max_iter= 10000000
activation='tanh'
estimatorsX=MLPClassifier(solver=solver, alpha=alpha, hidden_layer_sizes=hidden_layer_sizes, random_state=random_state,
                         max_iter=max_iter, activation=activation)

min_child_weight=1.5
max_depth=5
gamma=2.5
colsample_bytree=0.8
subsample=0.8
n_estimators=200
threads = 4
estimators = XGBClassifier(min_child_weight=min_child_weight,max_depth=max_depth, 
                           gamma=gamma,colsample_bytree=colsample_bytree,subsample=subsample,
                           n_estimators=n_estimators, n_jobs=threads
                          )
params = { 'max_features': [0.8,0.85,0.9,0.95,1.0],'max_samples':[0.6,0.65,0.7,0.75,0.8]}

#estimatorsY = LGBMClassifier(boosting_type='gbdt', num_leaves=40, max_depth=6,learning_rate=0.2,
 #                          n_estimators=1000,random_state=42)

#estimators = BaggingClassifier(base_estimator=estimatorsY,n_estimators=10,max_samples=0.65,
 #                            max_features=1.0, random_state=1,bootstrap=False)
#estimators = VotingClassifier( [('xgb', estimatorsX), ('mlp', estimatorsY)], weights=[1,1])
#estimators = GridSearchCV(estimator=estimatorsB, param_grid=params, cv=5)


In [ ]:
X_train, X_eval, y_train, y_eval = train_test_split(
    features_df,
    labels_df,
    test_size=0.33,
    shuffle=True,
    stratify=labels_df,
    random_state=2
)
smt = SMOTE(sampling_strategy='all', random_state=None, k_neighbors=5, n_jobs=1)
svmus = SVMSMOTE(sampling_strategy='auto',  k_neighbors=10, random_state=42,
                                n_jobs=4, out_step=0.1)
smottomek = SMOTETomek(sampling_strategy ='all', random_state=2, n_jobs=1)

#X_train, y_train = svmus.fit_resample(X_train, y_train)
full_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("estimators", estimators),
])

full_pipeline.fit(X_train, y_train)
preds = full_pipeline.predict(X_eval)
y_preds = pd.DataFrame(
    preds,
    index = y_eval.index
)

f1 = f1_score(y_eval, y_preds)
print(f1)

In [ ]:
#print(full_pipeline.named_steps['estimators'].best_params_, full_pipeline.named_steps['estimators'].best_score_)
print(f1)

In [ ]:
test_features_df = pd.read_csv(DATA_PATH / "test.csv", 
                               index_col="tripid")

test_features_df = formatdata(test_features_df)
powerAll(test_features_df, exceptList,power)


test_probas = full_pipeline.predict(test_features_df)
test_preds = pd.DataFrame(
    {'prediction':test_probas},
    index = test_features_df.index
)

test_preds.to_csv(DATA_PATH / 'my_submission.csv', index=True)

print(confusion_matrix(y_eval, y_preds))
print(test_preds.prediction.value_counts())
print(f1)

In [ ]:
print(confusion_matrix(y_eval, y_preds))
print(test_preds.prediction.value_counts())
print(f1)

In [ ]:
#median
#0.9762502413593357
#1    8113
#0     463
#[[ 367  188]
 #[  58 5056]]

In [ ]:
#mean
#0.9754447022428461
#1    8124
#0     452
#[[ 370  185]
# [  69 5045]]

In [ ]:
#most_frequent
#0.9740121727369336
#1    8126
#0     450
#[[ 359  196]
# [  73 5041]]

In [ ]:
#constant
0.9746713070378964
#1    8123
#0     453
#[[ 366  189]
# [  73 5041]]